### ISSUE TITLE
Backwards compat?

### ISSUE THREAD

**Issue by thisgeek** [YusukeSano/iterm2-iceberg#1]
Is this backwards compatible to the current non-beta release (3.4.16) of iTerm2? When I loaded this up in my setup, the ANSI colors look wrong:

<img width="927" alt="Screen Shot 2022-10-03 at 13 15 29" src="https://user-images.githubusercontent.com/20053/193638632-2f9500ea-bd87-4330-9caf-d0db4695f29b.png">

**Comment by YusukeSano** [comment]
Thanks for using it!

iTerm2 3.4.x uses two files, `Iceberg Light.itermcolors` and `Iceberg Dark.itermcolors`.
(`Iceberg.itermcolors` is the file for 3.5.x(beta))
https://github.com/YusukeSano/iterm2-iceberg#how-to-use

For automatic theme switching in 3.4.x, please refer to the following page.
https://gist.github.com/FradSer/de1ca0989a9d615bd15dc6eaf712eb93

**Comment by thisgeek** [comment]
Copy that. Iceberg Dark set on my env and looking good so far. Thanks for making it!
